# Generated by Django 5.0.2 on 2025-08-12 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_directory_fileblob_filechunk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WrappedKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrap_iv', models.BinaryField()),
                ('wrapped_key', models.BinaryField()),
                ('permission', models.CharField(default='read', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrapped_keys', to='storage.fileblob')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrapped_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('file', 'recipient')},
            },
        ),
    ]
