# Generated by Django 5.0.2 on 2025-08-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_wrappedkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrappedkey',
            name='owner_pub_jwk',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
