# Generated by Django 5.0.2 on 2025-08-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_wrappedkey_owner_pub_jwk'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileblob',
            name='manifest_algo',
            field=models.CharField(default='sha256', max_length=16),
        ),
        migrations.AddField(
            model_name='fileblob',
            name='manifest_root',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileblob',
            name='manifest_sig',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileblob',
            name='manifest_version',
            field=models.IntegerField(default=1),
        ),
    ]
